// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import loaders "github.com/testdouble/http-assertion-tool/loaders"
import mock "github.com/stretchr/testify/mock"

// FileLoader is an autogenerated mock type for the FileLoader type
type FileLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *FileLoader) Load(_a0 string) (*loaders.File, error) {
	ret := _m.Called(_a0)

	var r0 *loaders.File
	if rf, ok := ret.Get(0).(func(string) *loaders.File); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loaders.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
