// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0, _a1
func (_m *Loader) Load(_a0 string, _a1 chan error) chan string {
	ret := _m.Called(_a0, _a1)

	var r0 chan string
	if rf, ok := ret.Get(0).(func(string, chan error) chan string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan string)
		}
	}

	return r0
}
