// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import loaders "github.com/testdouble/http-assertion-tool/loaders"
import mock "github.com/stretchr/testify/mock"
import parsers "github.com/testdouble/http-assertion-tool/parsers"

// SpecParser is an autogenerated mock type for the SpecParser type
type SpecParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: _a0
func (_m *SpecParser) Parse(_a0 *loaders.File) (*parsers.Spec, error) {
	ret := _m.Called(_a0)

	var r0 *parsers.Spec
	if rf, ok := ret.Get(0).(func(*loaders.File) *parsers.Spec); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parsers.Spec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*loaders.File) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
