// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import loaders "github.com/testdouble/diplomat/loaders"
import mock "github.com/stretchr/testify/mock"

// Streamer is an autogenerated mock type for the Streamer type
type Streamer struct {
	mock.Mock
}

// Stream provides a mock function with given fields: _a0
func (_m *Streamer) Stream(_a0 string) (chan *loaders.Body, chan error) {
	ret := _m.Called(_a0)

	var r0 chan *loaders.Body
	if rf, ok := ret.Get(0).(func(string) chan *loaders.Body); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *loaders.Body)
		}
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(string) chan error); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}
