// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import builders "github.com/testdouble/diplomat/builders"
import mock "github.com/stretchr/testify/mock"

// Transformer is an autogenerated mock type for the Transformer type
type Transformer struct {
	mock.Mock
}

// Transform provides a mock function with given fields: _a0
func (_m *Transformer) Transform(_a0 builders.Test) (builders.Test, error) {
	ret := _m.Called(_a0)

	var r0 builders.Test
	if rf, ok := ret.Get(0).(func(builders.Test) builders.Test); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(builders.Test)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(builders.Test) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransformAll provides a mock function with given fields: _a0, _a1
func (_m *Transformer) TransformAll(_a0 chan builders.Test, _a1 chan error) chan builders.Test {
	ret := _m.Called(_a0, _a1)

	var r0 chan builders.Test
	if rf, ok := ret.Get(0).(func(chan builders.Test, chan error) chan builders.Test); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan builders.Test)
		}
	}

	return r0
}
