// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import parsers "github.com/testdouble/diplomat/parsers"

// Transformer is an autogenerated mock type for the Transformer type
type Transformer struct {
	mock.Mock
}

// Transform provides a mock function with given fields: _a0, _a1
func (_m *Transformer) Transform(_a0 chan parsers.Test, _a1 chan error) chan parsers.Test {
	ret := _m.Called(_a0, _a1)

	var r0 chan parsers.Test
	if rf, ok := ret.Get(0).(func(chan parsers.Test, chan error) chan parsers.Test); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan parsers.Test)
		}
	}

	return r0
}
