// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import colors "github.com/testdouble/diplomat/colors"
import mock "github.com/stretchr/testify/mock"

// Colorizer is an autogenerated mock type for the Colorizer type
type Colorizer struct {
	mock.Mock
}

// Paint provides a mock function with given fields: str, color
func (_m *Colorizer) Paint(str string, color colors.Color) string {
	ret := _m.Called(str, color)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, colors.Color) string); ok {
		r0 = rf(str, color)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
