// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import colors "github.com/testdouble/diplomat/colors"
import mock "github.com/stretchr/testify/mock"

// Colorizer is an autogenerated mock type for the Colorizer type
type Colorizer struct {
	mock.Mock
}

// Print provides a mock function with given fields: str, color
func (_m *Colorizer) Print(str string, color colors.Color) {
	_m.Called(str, color)
}
