// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Print provides a mock function with given fields: str
func (_m *Logger) Print(str string) {
	_m.Called(str)
}

// PrintAll provides a mock function with given fields: _a0, _a1
func (_m *Logger) PrintAll(_a0 chan string, _a1 chan error) {
	_m.Called(_a0, _a1)
}
