// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import runners "github.com/testdouble/diplomat/runners"

// ResultsPrinter is an autogenerated mock type for the ResultsPrinter type
type ResultsPrinter struct {
	mock.Mock
}

// Print provides a mock function with given fields: _a0, _a1
func (_m *ResultsPrinter) Print(_a0 chan runners.TestResult, _a1 chan error) {
	_m.Called(_a0, _a1)
}
