// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import builders "github.com/testdouble/diplomat/builders"
import mock "github.com/stretchr/testify/mock"
import parsers "github.com/testdouble/diplomat/parsers"

// SpecBuilder is an autogenerated mock type for the SpecBuilder type
type SpecBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: _a0
func (_m *SpecBuilder) Build(_a0 parsers.Spec) (builders.Test, error) {
	ret := _m.Called(_a0)

	var r0 builders.Test
	if rf, ok := ret.Get(0).(func(parsers.Spec) builders.Test); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(builders.Test)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(parsers.Spec) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuildAll provides a mock function with given fields: _a0
func (_m *SpecBuilder) BuildAll(_a0 chan parsers.Spec) chan builders.Test {
	ret := _m.Called(_a0)

	var r0 chan builders.Test
	if rf, ok := ret.Get(0).(func(chan parsers.Spec) chan builders.Test); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan builders.Test)
		}
	}

	return r0
}
